### ISSUE TITLE
Number  field

### ISSUE THREAD

**Issue by NicholasTing** [kitagry/contentful-go#8]
Just wondering, is it possible to create an entry using Integer / Number? 

```
resource "contentful_entry" "simple_content" {
  entry_id       = "simple_content_entry"
  space_id       = "develop"
  contenttype_id = contentful_contenttype.simple_content_type.id
  locale         = "en-US"
  field {
    id      = "text_field"
    content = "Hello, World Nick!"
    locale  = "en-US"
  }

  # field {
  #   id      = "number_field"
  #   content = 2
  #   locale  = "en-US"
  # }

  published  = false
  archived   = false
  depends_on = [contentful_contenttype.simple_content_type]
}
```

**Comment by NicholasTing** [comment]
reason is im getting an error when creating number fields

**Comment by kitagry** [comment]
Thank you for the issue! Currently, [terraform provider sdk doesn't support `any` type](https://github.com/hashicorp/terraform-plugin-sdk/issues/1204). So, if it will be implemented, I will fix it. Or, you can make pull request here.

https://github.com/kitagry/terraform-provider-contentful/blob/main/contentful/resource_contentful_entry.go#L53

**Comment by NicholasTing** [comment]
yep! let me see what i can do, thanks kitagry :)
